---
title: "LIBS Classification"
external_link: ''
date: '2016-04-27T00:00:00Z'
slides: ''
summary: A little about my LIBS research!
tags: ''
image:
  caption: 2019 SciX Poster
  focal_point: Smart
---


My research primarily focuses on integrating machine learning and statistics methods to improve the interpretation and classification of laser induced breakdown spectroscopy (LIBS) data. Laser-induced breakdown spectroscopy (LIBS) relies on data visualizations to interpret experimental results of spectra data. Dendrograms are most commonly used for this task, however, there are a number of algorithmic issues that arise with this method. Thus, to limit the practical issues that arise within hierarchical clustering methods, my team integrated unsupervised learning methods to more effectively visualize and analyze LIBS spectra data. 


The initial algorithms proved to be rather sucesful and as a result they are now being applied to help identify unknown mineral samples from around the world. Minerals are frequently used in the construction of roads and buildings, but now they also serve as a critical compent in the manufacturing of high-tech electronics and next-generation vehicles. Apple and Tesla for example rely heavily on certain ores for the construction of their product's batteries. However, each country where these minerals are being obtained from have different regulations some with some countries having more ethical and envrionemntal cautious practices. Thus, our lab collected thousands of Ore samples and by combinging my initial algorithms with block chain methods we hope to be able to identify where the ores are coming from so that we can ensure that each sample is coming ethically sourced. 


This project is currently a work in progress, but if you are interested in learning more about my initial research you can find my abstract [HERE](paper.pdf) and my initial poster [HERE](PozsonyiovaSofiaPosterScix.pdf).

