---
title: "Diggity Daggity"
external_link: ''
date: '2016-04-27T00:00:00Z'
slides: ''
summary: Check out my DAG!
tags: ''
image:
  caption: DAG
  focal_point: Smart
---

Daggity is an awesome online tool that I recently learned about that helps you simplify the causal discovery process. In my final semester of college, I had the opportunity to dive into the causal discovery process and created a DAG (directed acyclic graph) to help me design a study that focused on the effect of comprehensive sex education on adolescent sexual activity. The overall goal of my study was to help with advising whether or not schools should implement comprehensive sexual education, and to help debunk the highly anticipated question of "Does sex ed increase sexual activity?".

DAGs are crucial in the causal discovery process as they provide a way to visually represent and better understand the key concepts. As you can see from my DAG there are causal, and non-causal pathways between my set exposure (Comprehensive Sex Ed) and outcome (Adolescent Sexual Activity), and it necessary to be able to identify and appropriately adjust for confounders and potential sources of bias as they can significantly hinder results. Once I was to visualize my knowledge of the situation I was able to go through and outline additional key analyses that would need to be run such as inverse probability weighting, mediation analysis, quasi-experimental design, and time-varying treatment setting. As you can see, there are several different avenues of investigation which can aid us in the causal discovery process to better understand how an exposure can affect an outcome, and a DAG is a great first step in study design...so get ready to get diggity with daggity!


You can find an outline of my study and causal discovery process [HERE](causalspeaker.pdf) and you can find the full presentation with speaker notes [HERE](causal.pptx) out! 
